FROM swarmus/embedded

# Install ROS requirements
RUN apt-get update && apt-get install -y \
  ros-noetic-desktop-full \
  ros-noetic-rosdoc-lite \
  ros-noetic-controller-manager \
  ros-noetic-joint-state-controller \
  ros-noetic-robot-state-publisher \
  ros-noetic-message-runtime \
  ros-noetic-xacro \
  ros-noetic-robot-localization \
  ros-noetic-move-base \
  ros-noetic-move-base-msgs \
  ros-noetic-actionlib \
  ros-noetic-tf2 \
  ros-noetic-tf2-ros \
  ros-noetic-tf2-geometry-msgs \
  ros-noetic-global-planner \
  ros-noetic-rtabmap-ros \
  ros-noetic-gmapping \
  ros-noetic-navigation \
  ros-noetic-turtlebot3-bringup \
  ros-noetic-turtlebot3-navigation \
  ros-noetic-turtlebot3-slam 
