name: Docker build image

on:
   pull_request:
     branches: [ master ]
     
jobs:
  build-embedded:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file embedded/Dockerfile --tag swarmus/embedded:latest        

  build-ros-melodic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ros/melodic/Dockerfile --tag swarmus/ros-melodic:latest
